#!/bin/bash

jar cf mario_tmp.jar -C MarioAI4J/target/classes . \
                     -C MarioAI4J-Playground/target/classes . \
                     -C MarioAI4J-Tournament/target/classes .

zip -d mario_tmp.jar MarioAgent.class

mv -f mario_tmp.jar mario.jar
